name: Metrics
on:
  schedule: [{cron: "0 6 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Project Overview
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/repo-overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          user: Cooksey99
          repo: nucleus
          base: header, activity, community
          plugin_lines: yes
          plugin_traffic: yes

      # Step 2: Community & Contributors
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/repo-community.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          user: Cooksey99
          repo: nucleus
          plugin_people: yes
          plugin_people_types: contributors, stargazers
          plugin_people_limit: 28

      # Step 3: Project Velocity
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/repo-velocity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          user: Cooksey99
          repo: nucleus
          plugin_followup: yes
          plugin_followup_sections: user # For repos, 'user' section shows repo-specific followup
